[source]
type = "N2N"
address = "relays-new.cardano-mainnet.iohk.io:3001"
min_depth = 1

[[reducers]]
type = "BalanceByAddress"

[storage]
type = "Postgres"
connection_params = "postgresql://scrolls@localhost/scrolls"

[chain]
type = "Mainnet"

[intersect]
type = "Point"
value = [ 67305077, "55c5a9ff1f292aa77046f6f4f95be25173444c2e52998245c7f6e0f2d8e40804" ]

[policy]
missing_data = "Skip"